import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
const font = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <>
          <div className="w-full sticky top-0 md:items-center md:justify-center backdrop-filter backdrop-blur-md bg-gradient-to-b from-black to-zinc-950 antialiased z-50  overflow-hidden">
            <Navbar />
          </div>
          {children}
        </>
      </body>
    </html>
  );
}
